### ISSUE TITLE
JointTrajectoryActionController: How the target is applied?

### ISSUE THREAD

**Issue by anefg** [PR2/pr2_controllers#372]
I have been trying to understand how the JointTrajectoryController works. Analysing the code I could see that the joint states are published on update method. In the same method, some code lines before, the trajectory is executed applying the effort

'joints_[i]->commanded_effort_ = effort;'

In simulation is there any node which manages this new target and sends it to gazebo?

Thanks in advance,

Ane

**Comment by trainman419** [comment]
I suggest you take a look at the [pr2_controller Tutorials](http://wiki.ros.org/pr2_controllers/Tutorials) and the [PR2 JointTrajectoryAction tutorial](http://wiki.ros.org/pr2_controllers/Tutorials/Moving%20the%20arm%20using%20the%20Joint%20Trajectory%20Action) in particular.
