### ISSUE TITLE
Indigo release?

### ISSUE THREAD

**Issue by mikeferguson** [PR2/pr2_controllers#373]
It appears that pr2_controller_msgs is not in Indigo -- and this is blocking https://github.com/ros-planning/moveit_metapackages/issues/5

Is there a timeline on PR2 in indigo? Or should we drop the moveit_full_pr2 metapackage for indigo?

**Comment by UltronDestroyer** [comment]
Give me a moment, I'll release this in Indigo.

**Comment by mikeferguson** [comment]
Thanks!

**Comment by davetcoleman** [comment]
+1

**Comment by k-okada** [comment]
+1, I have confirmed current source code work on indigo/gazebo https://github.com/PR2/pr2_common/pull/233

**Comment by mikeferguson** [comment]
Bump?

**Comment by UltronDestroyer** [comment]
@mikeferguson just waiting on https://github.com/ros/convex_decomposition/issues/1

**Comment by mikeferguson** [comment]
Just a bump -- looks like convext_decomposition got released 2 days ago and made the latest public sync. If you can get this released in the next week, we can probably get moveit_pr2 into the next sync of Indigo

**Comment by garaemon** [comment]
convex_decomposition has been released and could you release this package?

**Comment by UltronDestroyer** [comment]
Almost done.. had to release 10 stacks before this could be released.

**Comment by UltronDestroyer** [comment]
It has now been released https://github.com/ros/rosdistro/pull/6843

**Comment by mikeferguson** [comment]
Thanks! I'll try to get moveit_pr2 out later today.
